version: '3'
services:
  zendesk-kb:
    build: .
    restart: unless-stopped
    image: 'zendesk-kb'
    container_name: 'zendesk-kb'
    #network_mode: 'host'
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - DOCS_DIRECTORY = ${DOCS_DIRECTORY}
      - KEEP_DOCS = ${KEEP_DOCS}
      - MAX_FAILURES = ${MAX_FAILURES}
      - ZENDESK_API_KEY = ${ZENDESK_API_KEY}
      - ZENDESK_SUBDOMAIN = ${ZENDESK_SUBDOMAIN}
      - ZENDESK_SITEMAP = ${ZENDESK_SITEMAP}
      - SITEMAP_FILTER = ${SITEMAP_FILTER}
      - VOICEFLOW_KB_API_KEY = ${VOICEFLOW_KB_API_KEY}
      - ALWAYS_FORCE = ${ALWAYS_FORCE}
      - PREVIOUS_DAYS = ${PREVIOUS_DAYS}
      - DEBUG = ${DEBUG}
      - NODE_ENV = ${NODE_ENV}
      - PORT = ${PORT}
