version: '3'
services:
  zendesk-kb:
    build: .
    restart: unless-stopped
    image: 'zendesk-kb'
    container_name: 'zendesk-kb'
    network_mode: "host"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
